export const LANGUAGES = [
  { value: 'it', label: 'Italiano' },
  { value: 'en', label: 'English' },
];

const TEXT = {
  it: {
    explore: 'Esplora', geometry: 'Geometria', data: 'Dati', settings: 'Impostazioni',
    layer: 'Layer', activeLayer: 'Layer attivo', addLayer: 'Aggiungi layer', addDataToProject: 'Aggiungi dati al progetto', defineNewVectorSchema: 'Definisci un nuovo schema vettoriale', importShpKmlGeojson: 'Importa SHP, KML, GeoJSON', noLayer: 'Nessun layer',
    createNewLayer: 'Crea nuovo layer', uploadExistingLayer: 'Carica layer esistente',
    crsProject: 'CRS progetto', changeCrs: 'Cambia CRS', lockedMenus: 'Menu bloccati',
    grid: 'Griglia', basemap: 'Mappa base', gps: 'GPS', scale: 'Scala', measure: 'Misura', area: 'Area', centerMap: 'Centra mappa', undoLastVertex: 'Annulla ultimo vertice', undo: 'Annulla', scaleLockedUnlock: 'Scala bloccata. Tocca per sbloccare.', setLockScaleHint: 'Imposta e blocca scala, es. 1:10000', tapPoint: 'Punto da tap', active: 'attivo',
    pointInsert: 'Inserimento punti', pointInsertHelp: 'Tocca la mappa per aggiungere punti. Trascina con due dita per spostarti senza creare punti.',
    createLayer: 'Crea layer', uploadLayer: 'Carica layer', backToLayers: '← Torna alla lista layer',
    output: 'destinazione', outputDestination: 'Destinazione esportazione', outputFile: 'File di uscita', outputFolder: 'Cartella di destinazione',
    fullFilePath: 'Percorso completo file', choose: 'Scegli', chooseFolder: 'Scegli cartella', chooseOutputFile: 'Scegli file di output',
    browserDownload: 'Download del browser', useBrowserDownload: 'Usa download del browser', notSelected: 'Non selezionato', defaultValue: 'Valore predefinito', defaultLabel: 'Predefinito',
    fileName: 'Nome file', extension: 'Estensione', export: 'Esporta', exportHelp: 'Scegli nome, estensione, percorso e CRS.',
    allLayers: 'Tutti i layer', feature: 'feature', features: 'feature', geom: 'Geom', dateTime: 'Data/Ora', actions: 'Azioni',
    noFeatures: 'Nessuna feature raccolta', noFeaturesHelp: 'Usa “Geometria” dalla mappa per raccogliere punti, linee o poligoni, oppure importa un file dalla sezione Carica.',
    featureProperties: 'Proprietà feature', coordinates: 'Coordinate', delete: 'Elimina', cancel: 'Annulla', saveChanges: 'Salva modifiche',
    language: 'Lingua', interfaceLanguage: 'Lingua interfaccia', italian: 'Italiano', english: 'English',

    appStartupError: 'Errore di avvio WebGIS', runtimeError: 'L’app ha intercettato un errore di esecuzione invece di mostrare una schermata nera.', clearLocalDataReload: 'Cancella dati locali e ricarica',
    mapEngine: 'Motore WebGIS', statusOperational: 'Stato: operativo', latitude: 'Latitudine', longitude: 'Longitudine', highPrecisionGps: 'GPS alta precisione',
    attributeTable: 'Tabella attributi', deleteFeatureConfirm: 'Eliminare questa feature?', allLayersSlug: 'tutti_layer', exportGis: 'Esporta GIS', projectCrsOption: 'CRS progetto', layerCrsOption: 'CRS layer', customEpsg: 'EPSG personalizzato',
    folderChoiceHelp: 'La scelta cartella funziona sui browser compatibili. Su Safari/Firefox/alcuni Android si userà il download standard.',
    goTo: 'Vai a', goToCoordinates: 'Vai a coordinate', enterCoordinatesInSelectedCrs: 'Inserisci coordinate nel CRS selezionato', lockScale: 'Blocca scala', scaleLockHelp: 'La distanza della scala resta visibile; zoom e pinch sono bloccati fino allo sblocco.', selectPointLayer: 'seleziona un layer puntuale',
    hideGrid: 'Nascondi griglia', showGrid: 'Mostra griglia', measureDistanceArea: 'Misura distanza / area',
    unlockCrsLayerMenus: 'Sblocca menu CRS e layer', lockCrsLayerMenus: 'Blocca menu CRS e layer',
    symbology: 'Simbologia', renderMode: 'Modalità resa', singleColor: 'Colore unico', byAttribute: 'Per attributo', layerColor: 'Colore layer', custom: 'Personalizzato', attribute: 'Attributo', noAttributesDefined: 'Nessun attributo definito. Aggiungi prima i campi nello schema del layer.', selectAttribute: '— Seleziona attributo —', colorRules: 'Regole colore', addRule: 'Aggiungi regola', addRuleHelp: 'Tocca “Aggiungi regola” per definire un colore per uno specifico valore attributo.', attributeValuePlaceholder: 'Valore attributo...', optionalLabel: 'Etichetta (opzionale)', otherValuesBaseColor: 'Tutti gli altri valori → colore base del layer', layerIndex: 'Indice layer', manageLayers: 'Gestisci layer', createOrImportLayerHelp: 'Crea un nuovo layer o importa un file GeoJSON / KML usando i pulsanti in basso.',
    geometryType: 'Tipo geometria', layerName: 'Nome layer', format: 'Formato', browserOnlyUnsupported: 'Non supportato in modalità solo browser', pointOnly: 'Solo punti', formatNotExportableBrowser: 'non è esportabile direttamente dal browser. L’esportazione sarà disponibile solo tramite strumenti desktop (QGIS, ecc.).', attributeSchema: 'Schema attributi', addField: 'Aggiungi campo', chooseNewLayerDestination: 'Scegli dove salvare il nuovo layer.', nameRequired: 'Il nome del layer è obbligatorio.', duplicateLayerNamePrefix: 'Esiste già un layer chiamato', duplicateLayerNameSuffix: 'Scegli un nome diverso.', addAtLeastOneField: 'Aggiungi almeno un campo con un nome.', layerCreatedFileWriteFailed: 'Layer creato nel progetto, ma non riesco a scrivere il file nel percorso scelto.', selectFolderFailed: 'Impossibile selezionare la cartella:', selectFileFailed: 'Impossibile selezionare il file:',
    importFile: 'Importa file', tapToSelectData: 'Tocca per selezionare dati + .prj opzionale', supportedFormatsShort: 'GeoJSON · JSON · KML · PRJ opzionale', layerCrs: 'CRS layer', crsImportHelp: 'Se il CRS non viene rilevato da GeoJSON/KML/PRJ, selezionalo qui prima di importare.', browserSupport: 'Supporto browser', geojsonSupport: '✓ GeoJSON / JSON FeatureCollection', kmlSupport: '✓ KML Point/Line/Polygon', prjSupport: '✓ Rilevamento CRS da .prj opzionale quando è presente autorità EPSG/WKT', unsupportedDesktopFormats: '⊘ Shapefile/GPKG/GeoTIFF richiedono librerie browser dedicate o backend GDAL.', importing: 'Importazione...', importLayer: 'Importa layer', selectFileFirst: 'Seleziona prima un file.', unsupportedImportFormat: 'Formato non supportato per l’importazione browser.', invalidGeoJson: 'Il file non è un GeoJSON valido (deve essere Feature o FeatureCollection).', invalidKml: 'KML non valido:', noGeometryInKml: 'Nessuna geometria trovata nel file KML.', unableReadFile: 'Impossibile leggere il file.', crsNotDetected: 'CRS non rilevato automaticamente. Conferma o modifica EPSG prima di importare.',
    projectCrsTitle: 'CRS progetto', projectCrsOverride: 'Sovrascrivi CRS progetto', projectCrsHelp: 'Usa il CRS progetto per coordinate, misure ed esportazioni quando è trasformabile.', applyEpsg: 'Applica EPSG', crsSearchPlaceholder: 'Cerca codice EPSG, nome CRS o paese, es. 32632, UTM, Italia', searchOnlineHelp: 'Cerca online quando disponibile; risultati e definizioni vengono salvati localmente per l’uso offline.', activeProjDefinition: 'Definizione PROJ attiva', epsgCatalog: 'Catalogo EPSG dinamico', searching: 'ricerca...', proj4Active: 'proj4 attivo — trasformazioni CRS abilitate', projUnavailableMetadata: 'Definizione PROJ non disponibile — salvato solo come metadato', projDefinitionUnavailable: 'Definizione non disponibile. Il CRS viene comunque salvato, ma le trasformazioni sono disabilitate finché non viene registrata una definizione PROJ.', selectedCrsLabel: 'CRS selezionato', loadingCrsDefinition: 'Caricamento definizione CRS...', crsRegisteredProj4: 'registrato con proj4.', crsSavedNoProj: 'salvato. Nessuna definizione PROJ trovata nel browser.', customCrs: 'CRS personalizzato', invalidCustomCrs: 'CRS personalizzato non valido. Usa una stringa PROJ, ad esempio +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs.', registeredCustomCrs: 'registrato come CRS personalizzato.', addCustomCrs: 'Aggiungi CRS personalizzato', customCrsCodePlaceholder: 'Codice, es. CUSTOM:UTM32 o EPSG:999999', projStringPlaceholder: 'Incolla stringa PROJ, es. +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs', registerCustomCrs: 'Registra CRS personalizzato', display: 'Visualizzazione', themePreviewHelp: 'L’anteprima del tema è immediata; Salva modifiche la rende permanente.', unitsHelp: 'Influisce su scala, misure e visualizzazione coordinate.', compassMode: 'Modalità bussola', compassModeHelp: 'Ruota la mappa in base all’orientamento del dispositivo.', hardwareAcceleration: 'Accelerazione hardware', hardwareAccelerationHelp: 'Suggerimento compositing GPU CSS per le tile mappa.', debugLog: 'Log debug', debugLogHelp: 'Scrive log dettagliati nella console del browser.', detailed: 'Dettagliato', off: 'Spento', showTutorialAgainHelp: 'Mostra di nuovo il tutorial iniziale.',
    onboardingHighlight: 'In evidenza', skip: 'Salta', back: 'Indietro', next: 'Avanti', start: 'Inizia',
    coordinateReference: 'Riferimento coordinate', sensorsSystem: 'Sensori e sistema', help: 'Aiuto', quickGuide: 'Guida rapida', showTutorial: 'Mostra tutorial',
    resetDefaults: 'Ripristina predefiniti', theme: 'Tema', units: 'Unità', metric: 'Metrico', imperial: 'Imperiale', light: 'Chiaro', dark: 'Scuro',
    apply: 'Applica', add: 'Aggiungi', name: 'Nome', type: 'Tipo', fields: 'Campi', fieldName: 'Nome campo', fieldType: 'Tipo campo',
    point: 'Punto', line: 'Linea', polygon: 'Poligono', table: 'Tabella', string: 'Testo', integer: 'Intero', double: 'Decimale', date: 'Data', boolean: 'Booleano',
    selectedFolder: 'Cartella selezionata', selectedFile: 'File selezionato', unknown: 'Sconosciuto', selectedCrs: 'CRS selezionato', directSave: 'Salvataggio diretto', directSaveHelp: 'La web app scriverà nella cartella scelta, se il browser mantiene il permesso.', selectedFileHelp: 'Il file è stato scelto con il selettore del browser e verrà sovrascritto al salvataggio.', browserDownloadHelp: 'Il file verrà scaricato nella cartella Download gestita dal browser. Il percorso mostrato è indicativo, non un percorso fisico garantito.', browserDownloadDefaultHelp: 'Nessuna cartella reale selezionata: verrà usato il download standard del browser.', downloadsFolderHint: 'Download del browser', chooseDestination: 'Scegli', changeDestination: 'Cambia', androidDownloadHint: 'Su Android cerca il file in Gestione file → Download oppure nella cronologia download del browser.',
  },
  en: {
    explore: 'Explore', geometry: 'Geometry', data: 'Data', settings: 'Settings',
    layer: 'Layer', activeLayer: 'Active layer', addLayer: 'Add layer', addDataToProject: 'Add data to project', defineNewVectorSchema: 'Define a new vector schema', importShpKmlGeojson: 'Import SHP, KML, GeoJSON', noLayer: 'No layer',
    createNewLayer: 'Create new layer', uploadExistingLayer: 'Load existing layer',
    crsProject: 'Project CRS', changeCrs: 'Change CRS', lockedMenus: 'Menus locked',
    grid: 'Grid', basemap: 'Basemap', gps: 'GPS', scale: 'Scale', measure: 'Measure', area: 'Area', centerMap: 'Center map', undoLastVertex: 'Undo last vertex', undo: 'Undo', scaleLockedUnlock: 'Scale locked. Tap to unlock.', setLockScaleHint: 'Set and lock scale, e.g. 1:10000', tapPoint: 'Tap point', active: 'active',
    pointInsert: 'Point insertion', pointInsertHelp: 'Tap the map to add points. Drag with two fingers to pan without creating points.',
    createLayer: 'Create layer', uploadLayer: 'Load layer', backToLayers: '← Back to layer list',
    output: 'Output', outputDestination: 'Output destination', outputFile: 'Output file', outputFolder: 'Output folder',
    fullFilePath: 'Full file path', choose: 'Choose', chooseFolder: 'Choose folder', chooseOutputFile: 'Choose output file',
    browserDownload: 'Browser download', useBrowserDownload: 'Use browser download', notSelected: 'Not selected', defaultValue: 'Default value', defaultLabel: 'Default',
    fileName: 'File name', extension: 'Extension', export: 'Export', exportHelp: 'Choose name, extension, path and CRS.',
    allLayers: 'All layers', feature: 'feature', features: 'features', geom: 'Geom', dateTime: 'Date/Time', actions: 'Actions',
    noFeatures: 'No collected features', noFeaturesHelp: 'Use “Geometry” from the map to collect points, lines or polygons, or import a file from Load.',
    featureProperties: 'Feature properties', coordinates: 'Coordinates', delete: 'Delete', cancel: 'Cancel', saveChanges: 'Save changes',
    language: 'Language', interfaceLanguage: 'Interface language', italian: 'Italiano', english: 'English',

    appStartupError: 'WebGIS startup error', runtimeError: 'The app caught a runtime error instead of showing a black screen.', clearLocalDataReload: 'Clear local data and reload',
    mapEngine: 'WebGIS engine', statusOperational: 'Status: operational', latitude: 'Latitude', longitude: 'Longitude', highPrecisionGps: 'High precision GPS',
    attributeTable: 'Attribute table', deleteFeatureConfirm: 'Delete this feature?', allLayersSlug: 'all_layers', exportGis: 'GIS export', projectCrsOption: 'Project CRS', layerCrsOption: 'Layer CRS', customEpsg: 'Custom EPSG',
    folderChoiceHelp: 'Folder selection works in compatible browsers. Safari/Firefox/some Android browsers will use the standard download.',
    goTo: 'Go to', goToCoordinates: 'Go to coordinates', enterCoordinatesInSelectedCrs: 'Enter coordinates in the selected CRS', lockScale: 'Lock scale', scaleLockHelp: 'The scale distance remains visible; zoom and pinch are locked until unlocked.', selectPointLayer: 'select a point layer',
    hideGrid: 'Hide grid', showGrid: 'Show grid', measureDistanceArea: 'Measure distance / area',
    unlockCrsLayerMenus: 'Unlock CRS and layer menus', lockCrsLayerMenus: 'Lock CRS and layer menus',
    symbology: 'Symbology', renderMode: 'Render mode', singleColor: 'Single color', byAttribute: 'By attribute', layerColor: 'Layer color', custom: 'Custom', attribute: 'Attribute', noAttributesDefined: 'No attributes defined. Add fields to the layer schema first.', selectAttribute: '— Select attribute —', colorRules: 'Color rules', addRule: 'Add rule', addRuleHelp: 'Tap “Add rule” to define a color for a specific attribute value.', attributeValuePlaceholder: 'Attribute value...', optionalLabel: 'Label (optional)', otherValuesBaseColor: 'All other values → base layer color', layerIndex: 'Layer index', manageLayers: 'Manage layers', createOrImportLayerHelp: 'Create a new layer or import a GeoJSON / KML file using the buttons below.',
    geometryType: 'Geometry type', layerName: 'Layer name', format: 'Format', browserOnlyUnsupported: 'Not supported in browser-only mode', pointOnly: 'Points only', formatNotExportableBrowser: 'cannot be exported directly from the browser. Export will only be available through desktop tools (QGIS, etc.).', attributeSchema: 'Attribute schema', addField: 'Add field', chooseNewLayerDestination: 'Choose where to save the new layer.', nameRequired: 'Layer name is required.', duplicateLayerNamePrefix: 'A layer named', duplicateLayerNameSuffix: 'already exists. Choose a different name.', addAtLeastOneField: 'Add at least one field with a name.', layerCreatedFileWriteFailed: 'Layer created in the project, but I cannot write the file to the selected path.', selectFolderFailed: 'Unable to select folder:', selectFileFailed: 'Unable to select file:',
    importFile: 'Import file', tapToSelectData: 'Tap to select data + optional .prj', supportedFormatsShort: 'GeoJSON · JSON · KML · optional PRJ', layerCrs: 'Layer CRS', crsImportHelp: 'If the CRS is not detected from GeoJSON/KML/PRJ, select it here before importing.', browserSupport: 'Browser support', geojsonSupport: '✓ GeoJSON / JSON FeatureCollection', kmlSupport: '✓ KML Point/Line/Polygon', prjSupport: '✓ CRS detection from optional .prj when EPSG/WKT authority is present', unsupportedDesktopFormats: '⊘ Shapefile/GPKG/GeoTIFF require dedicated browser libraries or a GDAL backend.', importing: 'Importing...', importLayer: 'Import layer', selectFileFirst: 'Select a file first.', unsupportedImportFormat: 'Format not supported for browser import.', invalidGeoJson: 'The file is not valid GeoJSON (must be Feature or FeatureCollection).', invalidKml: 'Invalid KML:', noGeometryInKml: 'No geometry found in the KML file.', unableReadFile: 'Unable to read the file.', crsNotDetected: 'CRS not detected automatically. Confirm or edit EPSG before importing.',
    projectCrsTitle: 'Project CRS', projectCrsOverride: 'Project CRS override', projectCrsHelp: 'Use the project CRS for coordinates, measurements and exports when it is transformable.', applyEpsg: 'Apply EPSG', crsSearchPlaceholder: 'Search EPSG code, CRS name or country, e.g. 32632, UTM, Italy', searchOnlineHelp: 'Search online when available; results and definitions are saved locally for offline use.', activeProjDefinition: 'Active PROJ definition', epsgCatalog: 'Dynamic EPSG catalog', searching: 'searching...', proj4Active: 'proj4 active — CRS transformations enabled', projUnavailableMetadata: 'PROJ definition unavailable — saved as metadata only', projDefinitionUnavailable: 'Definition unavailable. The CRS is still saved, but transformations are disabled until a PROJ definition is registered.', selectedCrsLabel: 'Selected CRS', loadingCrsDefinition: 'Loading CRS definition...', crsRegisteredProj4: 'registered with proj4.', crsSavedNoProj: 'saved. No PROJ definition found in the browser.', customCrs: 'Custom CRS', invalidCustomCrs: 'Invalid custom CRS. Use a PROJ string, for example +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs.', registeredCustomCrs: 'registered as custom CRS.', addCustomCrs: 'Add custom CRS', customCrsCodePlaceholder: 'Code, e.g. CUSTOM:UTM32 or EPSG:999999', projStringPlaceholder: 'Paste PROJ string, e.g. +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs', registerCustomCrs: 'Register custom CRS', display: 'Display', themePreviewHelp: 'Theme preview is immediate; Save changes makes it permanent.', unitsHelp: 'Affects scale, measurements and coordinate display.', compassMode: 'Compass mode', compassModeHelp: 'Rotates the map according to device orientation.', hardwareAcceleration: 'Hardware acceleration', hardwareAccelerationHelp: 'CSS GPU compositing hint for map tiles.', debugLog: 'Debug log', debugLogHelp: 'Writes detailed logs to the browser console.', detailed: 'Detailed', off: 'Off', showTutorialAgainHelp: 'Show the initial tutorial again.',
    onboardingHighlight: 'Highlighted', skip: 'Skip', back: 'Back', next: 'Next', start: 'Start',
    coordinateReference: 'Coordinate reference', sensorsSystem: 'Sensors and system', help: 'Help', quickGuide: 'Quick guide', showTutorial: 'Show tutorial',
    resetDefaults: 'Reset defaults', theme: 'Theme', units: 'Units', metric: 'Metric', imperial: 'Imperial', light: 'Light', dark: 'Dark',
    apply: 'Apply', add: 'Add', name: 'Name', type: 'Type', fields: 'Fields', fieldName: 'Field name', fieldType: 'Field type',
    point: 'Point', line: 'Line', polygon: 'Polygon', table: 'Table', string: 'String', integer: 'Integer', double: 'Double', date: 'Date', boolean: 'Boolean',
    selectedFolder: 'Selected folder', selectedFile: 'Selected file', unknown: 'Unknown', selectedCrs: 'Selected CRS', directSave: 'Direct save', directSaveHelp: 'The web app will write to the selected folder if the browser keeps the permission.', selectedFileHelp: 'The file was selected with the browser picker and will be overwritten on save.', browserDownloadHelp: 'The file will be downloaded to the folder managed by the browser. The displayed path is indicative, not a guaranteed physical path.', browserDownloadDefaultHelp: 'No real folder selected: the standard browser download will be used.', downloadsFolderHint: 'Browser downloads', chooseDestination: 'Choose', changeDestination: 'Change', androidDownloadHint: 'On Android, look for the file in Files → Downloads or in the browser download history.',
  },
};

export function t(language, key) {
  const lang = language === 'en' ? 'en' : 'it';
  return TEXT[lang]?.[key] || TEXT.it[key] || key;
}

export function fieldTypeLabel(language, type) {
  const map = { String: 'string', Integer: 'integer', Double: 'double', Date: 'date', Boolean: 'boolean' };
  return t(language, map[type] || type);
}
